name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Package
        uses: BigWigsMods/packager@master

      - uses: actions/upload-artifact@v1.0.0
        with:
          name: RemixCheckclist-CI
          path: .release/RemixCheckList
